# Generated by Django 5.1.5 on 2025-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoproject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
