# Generated by Django 5.1.5 on 2025-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoproject", "0002_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
