# Generated by Django 5.1.5 on 2025-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoproject", "0003_book_cover_book_description_book_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
